name: redstone_database_mongo
description: MongoDB extension for redstone_database_plugin
version: 0.6.0
authors:
  - Stéphane Este-Gracias <sestegra@gmail.com>
  - Hadrien Lejard <hadrien.lejard@gmail.com>
homepage: https://github.com/dartsome/redstone_database_mongo

environment:
  sdk: '>=2.0.0-dev.67.0 <3.0.0'

dependencies:
  connection_pool:
    git:
      url: https://github.com/dartsome/redstone_2.git
      path: connection_pool
  mongo_dart: ^0.3.3
  redstone_database_plugin:
    git:
      url: https://github.com/dartsome/redstone_2.git
      path: redstone_database_plugin

dev_dependencies:
  redstone:
    git:
      url: https://github.com/dartsome/redstone_2.git
      path: redstone
  serializer_generator: ^0.8.2
  test: ^1.3.0

#dependency_overrides:
#  connection_pool:
#    path: ../connection_pool
#  redstone:
#    path: ../redstone
