name: redstone_web_socket
version: 0.3.0
description: A web socket plugin for Redstone.dart
author: Luiz Mineo <luiz.mineo@gmail.com>
homepage: http://redstonedart.org

environment:
  sdk: '>=2.0.0-dev.67.0 <3.0.0'

dependencies:
  redstone:
    git:
      url: https://github.com/dartsome/redstone_2.git
      path: redstone
  shelf_web_socket: ^0.2.2+4

dev_dependencies:
  test: ^1.3.0

#dependency_overrides:
#  redstone:
#    path: ../redstone
