name: connection_pool
version: 0.3.0
author: Luiz Mineo <luiz.mineo@gmail.com>
description: A generic connection pool
homepage: https://github.com/luizmineo/connection_pool

environment:
  sdk: '>=2.0.0-dev.67.0 <3.0.0'

dev_dependencies:
  test: ^1.2.0
